--- #YAML:1.0
name:               Mozilla-CA
version:            20110914
abstract:           Mozilla's CA cert bundle in PEM format
author:
    - Gisle Aas <gisle@activestate.com>
license:            mozilla_1_1 gpl-2 lgpl_2_1
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test:  0
requires:
    perl:  5.006
resources:
    repository:  http://github.com/gisle/mozilla-ca
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
